### ISSUE TITLE
color the habits in the list to match area plot

### ISSUE THREAD

**Issue by gnull** [thermobased/flask-webapp#14]
![image](https://github.com/thermobased/flask-webapp/assets/7102119/04882ebc-d0f4-4d24-887e-6ec004db853d)

The user can't know right now which habits on the left correspond to which colors on the area chart. Would be nice if we could color them with matching colors to make the correspondence clear.

One solution I see is: pick a color for each habit (either permanently storing it in the DB, or on each page load) add it as the background color of each habit in the list, and also set it as the color of the corresponding area ([Unovis allows that](https://unovis.dev/docs/xy-charts/Area#multiple-colors)).

We can find an open-source color palette and assign colors from there to habits randomly (of let user pick). [Here's](https://yeun.github.io/open-color/) an example.

Ivan

**Comment by thermobased** [comment]
done in 5168f43c89d677e8ae67179dae346271ffd1d7cc and 6ea6a01d5332732514a6aebfb5cf8d4af5af1708
