### ISSUE TITLE
Allow setting daily goals for habits

### ISSUE THREAD

**Issue by gnull** [thermobased/flask-webapp#17]
User may want to set a custom daily goal for each habit. We can use this info to normalize the area chart values with respect to each other.

For example. if you want to read 30min/day and run 2h/day it makes sense for 30m of reading to take as much area as 2h of running will take on the area/

This is related to https://github.com/thermobased/flask-webapp/issues/16, but not strictly dependent. If we have custom units, goals must be set in them.

**Comment by thermobased** [comment]
Added in these commits: 4c0c5d830958b336bf248c374266e1d81734b12e, ec99623632f516e029cd67556953825ec12d8925, ab293c9518385e6c8eab86abb37e355629967f0c
