### ISSUE TITLE
Implement persistent login sessions through cookies

### ISSUE THREAD

**Issue by gnull** [thermobased/flask-webapp#2]
Right now, the app's main page `/` always displays login and register forms. Even after user has logged in.

We need to use cookies to remember that user has logged in, and change the behavior of the main page based on that.

 - If user is logged in, the `/` must display message "hello, $user" and have a logout button.
 - If user is not logged in, the `/` page must show the register and login forms.

See [flask docs](https://flask.palletsprojects.com/en/3.0.x/quickstart/#cookies) on using cookies.

Ivan

**Comment by thermobased** [comment]
fixed by 6195b1a
