### ISSUE TITLE
Datapoint deletion may erase other users' data

### ISSUE THREAD

**Issue by gnull** [thermobased/flask-webapp#9]
https://github.com/thermobased/flask-webapp/blob/bc938fa015090d7f46bfcf661d026edc26875b90/main.py#L188-L190

These SQL queries remove lines ignoring the user those belong to. We need to make sure that we delete only points of the current user, and leave the other entries intact.

Also: check if we have the same bug anywhere else.

Ivan

**Comment by thermobased** [comment]
fixed by 5409f1c00e02011ac8b75f40dd9dd34fe6c12ebc
